services:
  web:
    build:
      context: web
      dockerfile: ./Dockerfile.web
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
  server:
    build:
      context: api
      dockerfile: ./Dockerfile.api
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      db:

  db:
    image: mongo:jammy
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '27017:27017'
volumes:
  dbdata:


